apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    component: "airflow-dag"
  name: airflow-dag-pv
  namespace: airflow
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: airflow-dag
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: airflow
  name: airflow-dag-pvc
spec:
  selector:
    matchLabels:
      component: "airflow-dag"
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi